### ISSUE TITLE
Improve configurability of Detox

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#1238]
Currently, users have limited control over CLI and in-runner configuration of Detox. Besides, [commander-based](https://www.npmjs.com/package/commander) CLI  impedes any eventual implementation of documentation generation due to a conventional yet inconvenient string format required to configure options in the Detox commands. 

https://github.com/wix/Detox/blob/3899ea2b84a93c83071d113bd411d293dca1a8b4/detox/local-cli/detox-test.js#L29-L31

Consequently, keeping [APIRef.DetoxCLI.md](https://github.com/wix/Detox/blob/master/docs/APIRef.DetoxCLI.md) in sync with all the changes requires extra legwork and constant supervising.

A number of pull requests addressing various shortcomings in the configuration functionality have been emerging lately: #906, #1025, #1076, #1133, #1176. Therefore, it's the right time to enhance this aspect of Detox. 

I suggest to address those issues in a series of smaller pull requests and coordinate the work in this meta-issue:

- [ ] Move CLI to yargs (#1109) - provide more flexible API, open the potential for autodocumention and separate configuration files (#901)
- [ ] Deprecate --file and --specs (#1132⇦#1133, also resolved by #1109)
- [ ] Configuration in separate files (#901⇦#906)

To be continued.
