### ISSUE TITLE
Move away from Earl Grey's keyboard typing mechanism

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1476]
It is known to be buggy, finicky and limited:

https://github.com/wix/Detox/issues/1393
https://github.com/wix/Detox/issues/1254
https://github.com/wix/Detox/issues/902
https://github.com/wix/Detox/issues/677
https://github.com/google/EarlGrey/issues/31

As I proposed in https://github.com/google/EarlGrey/issues/439, I think there is a better solution than tapping actual software keyboard buttons. I think I can implement the keyboard functionality in a way that will be more stable and allow much more flexibility.

By calling the mid-level system API, it is possible to generate keyboard events regardless if the software keyboard is shown, as software or hardware events pass through this mid-level API:

```objc
@interface UIKeyboardTaskQueue : NSObject

- (void)performSingleTask:(void (^)(id))arg1;

@end

@interface UIKeyboardImpl : UIView

+ (instancetype)sharedInstance;
@property(readonly, nonatomic) UIKeyboardTaskQueue *taskQueue;
- (void)handleKeyWithString:(id)arg1 forKeyEvent:(id)arg2 executionContext:(id)arg3;

@end

…

[UIKeyboardImpl.sharedInstance.taskQueue performSingleTask:^(id ctx) {
	[UIKeyboardImpl.sharedInstance handleKeyWithString:@"ש" forKeyEvent:nil executionContext:ctx]; 
}];
```

##### Todo:

- [x] Alphanumeric key support (including unicode)
- [x] Return key support
- [x] Backspace key support
- [x] General keyboard keys support
- [x] Make keyboard noise

**Comment by elyalvarado** [comment]
@LeoNatan will this still show the keyboard on screen?
