### ISSUE TITLE
Add support for Genycloud emulators for grand PoC

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2429]
**Is your feature request related to a problem? Please describe.**
For the sake of running internal-PoC's at Wix, we need to enable support for [Genycloud](https://cloud.geny.io/)-based emulators. This mainly suggests a dedicated driver should be written to support that.

The work for a Detox-PoC has already been done by @EdenGottlieb in branch `genymotion-support-2`. Now need to pick it up from where it was left off, in order to achieve complete functionality.

---
Task list in order to be ready for a contract signing and a PoC at scale:
- [x] Initial naive support so as to start getting numbers running on OSS CI. [#2446]
- [x] An optimization of instance creation (i.e. usage of the --no-wait flag), with boot-up polling. [#2466]
- [x] Inherent device instances tear-down on global tear-down context. [#2471, #2529, wix-private/shono/pull/106]
- [x] Improve instance leaks warning-logs by maintaining instance names in cleanup registry. [#2476]
- [x] Instance leakage warning in case of abrupt termination (research, first - maybe with `signal-exit`) [#2555]
- [x] Detox user-agent
- [x] Reimplement `LookupService.getInstance()` using new gmsaas `1.6.0` command: `gmsaas instance get <uuid>` (also, need to add a prevalidation of that version is >= 1.6.0) [#2546]
