### ISSUE TITLE
[CI] Implement a workflow for testing regressions on a wide range of React Native versions

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#3854]
## Describe your idea

I'd suggest creating an automated exploratory testing flow that runs:

1. `npx react-native init TestProject --version X.XX.X`
2. Sets up Detox according to the "Getting Started" tutorial on the website.
3. Executs a hello-world test to confirm there are no blocker issues.

### Roadmap

- [ ] https://github.com/wix/Detox/issues/3415  (Phase 1, as the **iOS** implementation would be the easier part);
- [ ] Phase 2: **Android** implementation (blocked by #2743 unless we're okay to create a hacky solution with an extra maintenance cost);
- [ ] Phase 3: Migrate Detox E2E self-test project to a multiverse mode — maybe extract it to a separate repo with mainstream in `main` branch and separate Git branches for version-specific hacks and adjustments.

### Motivation

1. Detox project could benefit from the ability to check regularly new issues on new React Native versions.
2. Such flow would signalize possible regressions in older React Native versions we don't regularly check on CI. That would help to keep the "Supported versions" table in the README always up-to-date.

**Comment by d4vidi** [comment]
Thanks @noomorph! This aligns well with discussions we've had about this in the past (IIRC).
Mind this while this would definitely test Detox's fundamentals with respect to each target RN version, it may not be good enough in order to be able to call out that each version is indeed properly supported. For that, we have no choice but to go through the fully blown test suite.

**Comment by noomorph** [comment]
@d4vidi I agree that this won't be enough to claim support for a specific version with confidence. Still, I'm afraid that maintaining an E2E test project in a multiverse of React Native versions will be more than just challenging ~(read: nightmare)~.

Your idea is still legit, but I'd consider it a continuation of this effort, like "phase 3". It is going to be too hard from the beginning to achieve this degree of test coverage for arbitrary RN versions.

**Comment by d4vidi** [comment]
Sounds legit as well - but only as long as we don't over-bloat ourselves with a complex test matrix with many use cases; Taking into account here that the RN is an extremely fast-moving project, where old versions become outdated pretty fast.
