### ISSUE TITLE
[Epic] Selenium Grid 4 PoC

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#4055]
### Describe your idea

```[tasklist]
- [x] [SG4] Implement reusable logger
- [ ] https://github.com/wix/Detox/issues/4074
- [ ] https://github.com/wix/Detox/issues/4075
- [ ] https://github.com/wix/Detox/issues/4076
- [ ] https://github.com/wix/Detox/issues/4077
- [ ] https://github.com/wix/Detox/issues/4078
- [ ] https://github.com/wix/Detox/issues/4079
- [ ] https://github.com/wix/Detox/issues/4080
- [ ] https://github.com/wix/Detox/issues/4081
```
