### ISSUE TITLE
[Epic] React Native .72 Compatibility

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#4154]
```[tasklist]
- [ ] https://github.com/wix/Detox/issues/4155
- [ ] https://github.com/wix/Detox/issues/4156
- [ ] https://github.com/wix/Detox/issues/4157
- [ ] https://github.com/wix/Detox/issues/4158
- [ ] https://github.com/wix/Detox/issues/4159
- [ ] https://github.com/wix/Detox/issues/4160
```

**Comment by asafkorem** [comment]
Relevant: https://github.com/wix/Detox/issues/4148
