### ISSUE TITLE
./gradlew assembleDebug issue

### ISSUE THREAD

**Issue by uasghar-smile** [wix/Detox#4190]
### What happened?

I am trying to create a debug build.

But i am facing this error
Important: 'detox build' is a convenience shortcut for calling your own build command, as provided in the config file.
Failures in this build command are not the responsibility of Detox. You are responsible for maintaining this command.

Command failed: cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Simply run detox build --configuration android.att.debug  OR. detox build --configuration android.emu.debug

### In what environment did this happen?

Detox version: 20.12.0
React Native version: 0.68.6
Node version: 20.5.1
Device model:  OPPO A57
OS: Mac OS 12.6.8
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```
<img width="1114" alt="Screenshot 2023-09-15 at 6 04 22 PM" src="https://github.com/wix/Detox/assets/102786004/cf5f43bf-0925-43cb-bcf8-e0ed58679978">

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

### More data, please!

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```Detox version: 20.12.0
React Native version: 0.68.6
Node version: 20.5.1
Device model:  OPPO A57
OS: Mac OS 12.6.8
Test-runner (select one): jest


_No response_

**Comment by cunderw** [comment]
This is an issue with your build not detox. What are the rest of the build logs? Something failed compiling ```react-native-google-places``` but you haven't posted the full build logs.
