### ISSUE TITLE
Migrate permission commands to Simctl

### ISSUE THREAD

**Issue by asafkorem** [wix/Detox#4321]
Use Simctl instead of ASU (AppleSimUtils) where possible, utilizing Simctl capabilities like setting the Simulator geo-location (which wasn't possible before).

```[tasklist]
### Tasks
- [x] CI build issues: need to upgrade Xcode on CI agents (Xcode 15 is required).
- [x] Migrate commands to Simctl (in PR: #4301).
- [x] Update documentation (permissions & location).
- [x] Add E2E tests for setting device permissions.
- [x] Enable media-library tests once https://github.com/zoontek/react-native-permissions/pull/831 is merged.
```

**Comment by noomorph** [comment]
🥳
