### ISSUE TITLE
[Epic] Extend system interaction support

### ISSUE THREAD

**Issue by asafkorem** [wix/Detox#4464]
This epic extends the epic [System interactions on iOS](https://github.com/wix/Detox/issues/4432) to Android, and adds new functionalities for both platforms.

The initial support on iOS, which will now be mirrored on Android, includes:

```[tasklist]
### Tasks
- [ ] System matchers: `by.system.label`, `by.system.type`
- [ ] System actions: `tap()`
- [ ] System expectations: `toExist()`, `atIndex(..)`, `not` modifier
```

For Android, we will use UIAutomator (UIDevice) to achieve functional parity in areas where Espresso and current Detox APIs falls short.

The goal of this effort is to facilitate system-level interactions with operating system features such as alerts (dialogs), toasts, and more.

Upcoming enhancements will focus on enabling new features that leverage system-level interactions, including:

```[tasklist]
### Tasks
- [ ] System browser integration (Safari/Chrome)
- [ ] Push notifications handling
- [ ] In-app* system-level interactions
```

*Specifically required for embedded web-views that prevent JS injection and where our [webview APIs](https://wix.github.io/Detox/docs/api/webviews) are ineffective.

**Comment by d4vidi** [comment]
No ETA's ATM, we're planning to reevaluate the priority of Android related improvements soon enough though.
