### ISSUE TITLE
React Native .74 Compatibility

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#4484]
### Describe your idea

```[tasklist]
### Tasks
- [x] [RN74] iOS compat: Test Project
- [x] [RN74] iOS compat: Demo Project
- [x] [RN74] Android compat: Test Project
- [x] [RN74] Android compat: Demo Project
- [ ] [RN74] Internal rollout
- [ ] [RN74] Docs alignment
- [ ] https://github.com/wix/Detox/issues/3558
```

**Comment by corentinfoure** [comment]
Hello@d4vidi,
Has there been any progress on this ? I'm facing issues on RN .74.1 😕

**Comment by FaithfulAudio** [comment]
Hello! We are using this and recently changed our project to RN76 and find it seems incompatible with RN 76 Fabric architecture. Is 74 still in progress, and will it include fabric support?

**Comment by gosha212** [comment]
@FaithfulAudio Hi, thanks for the update. We are working hard to make Detox work on RN 74,75 and 76. It is the next task in our backlog, however we don't have any estimation.
