### ISSUE TITLE
[Epic] Detox Copilot

### ISSUE THREAD

**Issue by asafkorem** [wix/Detox#4576]
Detox Copilot is a Detox plugin that leverages large language models (LLM) to seamlessly invoke Detox actions.

It provides APIs to perform actions and assertions within your Detox tests while interfacing with an LLM service to enhance the testing process.

```[tasklist]
### Tasks
- [ ] https://github.com/wix/Detox/issues/4577
- [ ] https://github.com/wix/Detox/issues/4578
- [ ] https://github.com/wix/Detox/issues/4583
- [ ] https://github.com/wix/Detox/issues/4579
- [ ] https://github.com/wix/Detox/issues/4580
- [x] [Copilot] Support System interactions & platform specification
- [ ] https://github.com/wix/Detox/issues/4581
- [ ] https://github.com/wix/Detox/issues/4582
- [x] [Copilot] Write blog post introducing Detox Copilot
```

```[tasklist]
### Research
- [x] [Pilot] Research and POC
- [x] [Copilot] Optimization research: Cache
- [ ] [Copilot] Optimization research: Image downscale
- [ ] [Copilot] Optimization research: Different models
```

**Comment by d4vidi** [comment]
@asafkorem I'm actually ok with this being closed, it makes perfect sense for the remaining scope to be managed elsewhere...
