### ISSUE TITLE
Add more E2E suites for Detox Copilot (under the test app)

### ISSUE THREAD

**Issue by asafkorem** [wix/Detox#4634]
Implement the following Copilot E2E test suites for Detox:

- [ ] Device tap / long press - based on https://github.com/wix/Detox/blob/master/detox/test/e2e/06.device-tap.test.js
- [ ] Drag & drop tests - https://github.com/wix/Detox/blob/master/detox/test/e2e/28.drag-and-drop.test.js
- [ ] Permissions - based on https://github.com/wix/Detox/blob/master/detox/test/e2e/13.permissions.test.js
```[tasklist]
### Tasks
- [ ] Hybrid
```
