### ISSUE TITLE
React Native 75 compatibility

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#4646]
### Describe your idea

```[tasklist]
### Tasks
- [ ] [RN75] iOS compat: Test Project
- [ ] [RN75] iOS compat: Demo Project
- [ ] [RN75] Android compat: Test Project
- [ ] [RN75] Android compat: Demo Project
- [ ] [RN75] Internal rollout
- [ ] [RN75] Docs alignment
```
