### ISSUE TITLE
React Native 76 compatibility

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#4647]
### Describe your idea

```[tasklist]
### Tasks
- [x] [RN76] iOS compat: Test Project
- [x] [RN76] iOS compat: Demo Project
- [x] [RN76] Android compat: Test Project
- [x] [RN76] Android compat: Demo Project
- [x] [RN76] Internal rollout
- [x] [RN76] Docs alignment
- [ ] https://github.com/wix/Detox/issues/3558
```

**Comment by Acex187x** [comment]
Does Detox have any support of RN 76 for now? Just tried to run some e2e after update to 76 and it seems like test just hangs without any ability to control the app. Is it okay? Some estimate of when it will be resolved are much appreciated, thanks!

**Comment by gosha212** [comment]
@Acex187x Hi, the version is not release yet. Any way, we will support currently 76 without the new arch. You will need to opt-out in order to make it work. The new arch implementation is in progress https://github.com/wix/Detox/issues/4175

**Comment by Omnicpie** [comment]
@gosha212 If that's the case, is there any timeframe by which #4175 will be complete? As far as I (and a brand new React Native project) would be concerned, there is no compatibility with 0.76 until the new arch is supported.

**Comment by gosha212** [comment]
@Omnicpie  We can't estimate for sure because there are lots of unknown both in Android and iOS. I would estimate it in a few weeks - month. Currently you can opt out while waiting for the fix.

**Comment by Omnicpie** [comment]
@gosha212 some packages dropped support for the old architecture when bringing support for the new architecture (taking [react-native-mmkv](https://www.npmjs.com/package/react-native-mmkv) as my example here) so I'm not sure i entirely agree that simply opting-out is the solution, it would make a difference in package versioning as a whole, and could quite easily bring about other issues.  

For us, it means that we cannot move forward with the upgrade for 75 -> 76 until support is added.

**Comment by tmitchel2** [comment]
Give them a break @Omnicpie, it's compatible with 76 if you just turn the new architecture off.  If you're using a package that doesn't support the old architecture during this transition period then thats on you and your bad planning, not the detox devs.  But i presume even for the example you have given you could downgrade to v2?  Have you tried it?

Don't get me wrong, Im desperate myself for this to be working also but there are so many new arch bugs all over place on real devices and you just have to nudge it forwards as and when libs and core projects allow it.

**Comment by Omnicpie** [comment]
I'm not trying to be rude, so I'm sorry if that's how its coming across, I'm just trying to explain why the new arch should be a priority and some of my reasonings behind that.

Ofc it'll take as long as it needs to, I'm just very eager for it to move forward.

**Comment by noomorph** [comment]
It is challenging to migrate to the new RN versions and new arch at once — there are nontrivial fixes and changes to be made, and AFAIK @gosha212 is working on this matter. 

Very obscure logs, limited tooling to infer what some of those Looper messages mean - all that does not contribute to high velocity so his estimate is on realistic, if not on the optimistic side.

**Comment by champa-b** [comment]
> Does Detox have any support of RN 76 for now? Just tried to run some e2e after update to 76 and it seems like test just hangs without any ability to control the app. Is it okay? Some estimate of when it will be resolved are much appreciated, thanks!

still facing same ?

**Comment by gosha212** [comment]
@champa-b hi, it should work now with rn76.
Rn 76 new arch is already working on Android

**Comment by cuongnguyeneh** [comment]
> Rn 76 new arch is already working on Android

hi @gosha212 , Rn 76 is working well on Android. However it keeps hanging IOs test with this kind of issue:

```
The app is busy with the following tasks:
• 7 enqueued JavaScript timers:
  - Timer #1:
    + JS timer ID: 96.
    + Duration: 50.
    + Elapsed: 188.98093700408936.

  - Timer #2:
    + JS timer ID: 67.
    + Duration: 200.
    + Elapsed: 1005.139946937561.

  - Timer #3:
    + JS timer ID: 102.
    + Duration: 50.
    + Elapsed: 81.1699628829956.

  - Timer #4:
    + JS timer ID: 94.
    + Duration: 50.
    + Elapsed: 401.36194229125977.

  - Timer #5:
    + JS timer ID: 90.
    + Duration: 50.
    + Elapsed: 959.2350721359253.

  - Timer #6:
    + JS timer ID: 68.
    + Duration: 50.
    + Elapsed: 982.3410511016846.

  - Timer #7:
    + JS timer ID: 69.
    + Duration: 50.
    + Elapsed: 982.1310043334961.

• There are 5 pending React Native node animation updates.
• There are 1 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
• Run loop "Main Run Loop" is awake.
• 2 enqueued native timers:
  - Timer #1:
    + Fire date: none.
    + Time until fire: 0.000.
    + Repeat interval: 0.
    + Is recurring: YES.
  - Timer #2:
    + Fire date: none.
    + Time until fire: 0.000.
    + Repeat interval: 0.
    + Is recurring: YES.
```

Is this known issue ? btw my simulator is not interactable while running test.

**Comment by gosha212** [comment]
@cuongnguyeneh it should work. We have automated tests on our ci with RN 76. Please make sure you're using the latest version.
From the output it looks like you have some timers in your code
